GET http://localhost:3000/teams

###

GET http://localhost:3000/teams/5ebdc1f37123eaa5a0381f5f

###

POST http://localhost:3000/teams
Content-Type: application/json

{
  "name": "Gremio",
  "colorOne": "teal" 
}