GET http://localhost:3000/teams

###

GET http://localhost:3000/teams/5ec6d5ca74b991442c670664

###

POST http://localhost:3000/teams
Content-Type: application/json

{
  "name": "Flamego",
  "colorOne": "red" 
}


// Player routes

###

GET http://localhost:3000/players

###


GET http://localhost:3000/players/5ebaf979c6b65939d60e7461




